export enum NotificationType {
  // Cloud / Storage
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  FILE_MOVED = 'FILE_MOVED',

  // Archive
  ARCHIVE_CREATE_PROGRESS = 'ARCHIVE_CREATE_PROGRESS',
  ARCHIVE_CREATE_COMPLETE = 'ARCHIVE_CREATE_COMPLETE',
  ARCHIVE_CREATE_FAILED = 'ARCHIVE_CREATE_FAILED',
  ARCHIVE_EXTRACT_PROGRESS = 'ARCHIVE_EXTRACT_PROGRESS',
  ARCHIVE_EXTRACT_COMPLETE = 'ARCHIVE_EXTRACT_COMPLETE',
  ARCHIVE_EXTRACT_FAILED = 'ARCHIVE_EXTRACT_FAILED',

  // Folder Create (async)
  FOLDER_CREATE_PROGRESS = 'FOLDER_CREATE_PROGRESS',
  FOLDER_CREATE_COMPLETE = 'FOLDER_CREATE_COMPLETE',
  FOLDER_CREATE_FAILED = 'FOLDER_CREATE_FAILED',

  // Quota
  QUOTA_WARNING = 'QUOTA_WARNING',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // Team
  TEAM_INVITATION_RECEIVED = 'TEAM_INVITATION_RECEIVED',
  TEAM_INVITATION_ACCEPTED = 'TEAM_INVITATION_ACCEPTED',
  TEAM_INVITATION_DECLINED = 'TEAM_INVITATION_DECLINED',

  // Subscription
  SUBSCRIPTION_CHANGED = 'SUBSCRIPTION_CHANGED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',

  // Errors
  ERROR = 'ERROR',
  RATE_LIMIT = 'RATE_LIMIT',

  // Document
  DOCUMENT_CREATED = 'DOCUMENT_CREATED',
  DOCUMENT_UPDATED = 'DOCUMENT_UPDATED',
  DOCUMENT_LOCKED = 'DOCUMENT_LOCKED',
  DOCUMENT_UNLOCKED = 'DOCUMENT_UNLOCKED',

  // Duplicate Scan
  DUPLICATE_SCAN_PROGRESS = 'DUPLICATE_SCAN_PROGRESS',
  DUPLICATE_SCAN_COMPLETE = 'DUPLICATE_SCAN_COMPLETE',
  DUPLICATE_SCAN_FAILED = 'DUPLICATE_SCAN_FAILED',
  DUPLICATE_SCAN_CANCELLED = 'DUPLICATE_SCAN_CANCELLED',

  // API / Webhooks
  WEBHOOK_DELIVERY_FAILED = 'WEBHOOK_DELIVERY_FAILED',
  API_QUOTA_WARNING = 'API_QUOTA_WARNING',
  API_QUOTA_EXCEEDED = 'API_QUOTA_EXCEEDED',
}
